edited script, edited the group, and added new badge
aleen42/badges pull request #11
Opened 2021-04-04 15:15 UTC by BroJenuel

I edited the `setup.js` file, the `--dynamic-fore-color` should not be wrapped in an array for the npm build to work.

I also added a new group for social medias,
and added an Icon for the youtube.

2021-04-04 15:16 UTC, BroJenuel commented
I edited the setup.js file, the --dynamic-fore-color should not be wrapped in an array for the npm build to work.

I also added a new group for social medias,
and added an Icon for the youtube.

2021-04-06 05:16 UTC, aleen42 requested changes

2021-04-06 05:16 UTC, aleen42 commented on dist/youtube.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" style="fill:rgba(255, 0, 0, 1);transform:;-ms-filter:"><path d="M21.593,7.203c-0.23-0.858-0.905-1.535-1.762-1.766C18
It may be better to get from the official resources: https://www.youtube.com/about/brand-resources/#logos-icons-colors

2021-04-06 05:16 UTC, aleen42 commented on script/setup.js
> +            ...dfc ? '--dynamic-fore-color' : '',
You forgot to remove the spread operator.

2021-04-06 10:47 UTC, BroJenuel commented on script/setup.js
> +            ...dfc ? '--dynamic-fore-color' : '',
how to change it here? do I request a new pull?

2021-04-06 10:59 UTC, BroJenuel commented on dist/youtube.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" style="fill:rgba(255, 0, 0, 1);transform:;-ms-filter:"><path d="M21.593,7.203c-0.23-0.858-0.905-1.535-1.762-1.766C18
```suggestion
<svg id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 176 124"><defs><style>.cls-1{fill:#ee3124;}.cls-2{fill:#fff;}</style></defs><path class="cls-1" d="M180.32,53.36A22.12,22.12,0,0,0,164.76,37.7C151,34,96,34,96,34s-55,0-68.76,3.7A22.12,22.12,0,0,0,11.68,53.36C8,67.18,8,96,8,96s0,28.82,3.68,42.64A22.12,22.12,0,0,0,27.24,154.3C41,158,96,158,96,158s55,0,68.76-3.7a22.12,22.12,0,0,0,15.56-15.66C184,124.82,184,96,184,96S184,67.18,180.32,53.36Z" transform="translate(-8 -34)"/><polygon class="cls-2" points="70 88.17 70 35.83 116 62 70 88.17"/></svg>
```

this was taken in youtube

2021-04-06 11:11 UTC, merged

2021-04-06 11:16 UTC, aleen42 commented
@BroJenuel Thanks for your contribution.